import { useState } from 'react';
import { services, profile } from '../lib/site';
export default function Consulting() {
  const [status, setStatus] = useState('');
  function contact(event) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const body = '이름 / 팀: ' + data.get('name') + '\n회신 이메일: ' + data.get('email') + '\n상담 분야: ' + data.get('service') + '\n\n현재 상황과 고민:\n' + data.get('message');
    window.location.href = 'mailto:' + profile.email + '?subject=' + encodeURIComponent('[SOOD 상담] ' + data.get('service') + ' · ' + data.get('name')) + '&body=' + encodeURIComponent(body);
    setStatus('메일 앱으로 내용을 전달했습니다. 메일 앱에서 발송을 완료해 주세요. 앱이 열리지 않으면 아래 이메일로 직접 보내실 수 있습니다.');
  }
  return <div className="shell page-section"><p className="eyebrow">WORK WITH SOOD</p><h1 className="page-title">막연한 고민을,<br /><em>구체적인 다음 단계로.</em></h1><p className="lead">사업의 현재를 함께 짚고, 지금 필요한 실행을 설계합니다.</p><div className="consulting-services">{services.map(s => <section id={s.id} key={s.id} className="consulting-row"><span className="service-number">{s.number}</span><div><p className="eyebrow">{s.en}</p><h2>{s.title}</h2><p>{s.description}</p></div><ul>{s.outputs.map(o => <li key={o}>↗ {o}</li>)}</ul></section>)}</div><section className="process"><p className="eyebrow">HOW WE WORK</p><h2>대화에서 시작해 실행까지.</h2><div className="process-grid">{[['01', '상황 이해', '현재 사업과 고민, 기대하는 변화를 듣습니다.'], ['02', '범위 제안', '목표와 산출물, 일정과 비용을 협의합니다.'], ['03', '함께 실행', '합의한 과제를 진행하고 다음 행동을 정리합니다.']].map(([n,t,d]) => <div key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section><section className="contact-section" id="contact"><div><p className="eyebrow">LET’S TALK</p><h2>지금, 어떤 문제를<br />풀고 계신가요?</h2><p>정리된 계획서가 없어도 괜찮습니다.<br />현재 상황과 고민부터 들려주세요.</p><a className="contact-email" href={'mailto:' + profile.email}>{profile.email} ↗</a><p className="section-note">일정과 비용은 상담 범위에 따라 협의합니다.</p></div><form onSubmit={contact}><label htmlFor="name">이름 / 팀 또는 회사</label><input id="name" name="name" autoComplete="organization" required maxLength="100" placeholder="홍길동 / 팀 이름" /><label htmlFor="email">회신받을 이메일</label><input id="email" name="email" type="email" autoComplete="email" required maxLength="200" placeholder="hello@yourcompany.com" /><label htmlFor="service">함께 이야기할 분야</label><select id="service" name="service">{services.map(s => <option key={s.id}>{s.en}</option>)}<option>강의 · 콘텐츠 협업 · 기타</option></select><label htmlFor="message">현재 상황과 고민</label><textarea id="message" name="message" required rows="4" maxLength="3000" placeholder="어떤 사업을 하고 계신가요? 가장 고민되는 점을 알려주세요." /><p className="form-note">입력 내용으로 메일 앱이 열립니다. 직접 발송하기 전에는 상담이 접수되지 않습니다.</p><button className="button primary" type="submit">상담 메일 작성하기 ↗</button><p role="status" className="form-status">{status}</p></form></section></div>;
}
